import os
import shutil
import threading
from datetime import datetime
from typing import Any, Dict, List, Optional

from librift.utils import read_json, write_json


class ServerStorage:
    """Tracks FLIRT signature files generated by rift_server.py. Only used when remote mode enabled."""

    def __init__(self, logger, path):
        self.logger = logger
        self.path = os.path.abspath(path)
        self._lock = threading.RLock()
        self._index_path = os.path.join(self.path, "index.json")

        os.makedirs(self.path, exist_ok=True)
        self._index: Dict[str, Dict[str, Any]] = self._load_index()

    def _load_index(self) -> Dict[str, Dict[str, Any]]:
        """Load the on-disk index, if any."""
        if not os.path.isfile(self._index_path):
            return {}
        try:
            return read_json(self._index_path)
        except Exception as e:
            self.logger.warning(f"Failed to load storage index '{self._index_path}': {e}. Starting with an empty index.")
            return {}

    def _save_index(self) -> None:
        """Persist the current index to disk."""
        try:
            write_json(self._index_path, self._index)
        except Exception as e:
            self.logger.warning(f"Failed to save storage index '{self._index_path}': {e}")

    def register(self, source_path: str, job_id: Optional[str] = None) -> str:
        """
        Track a generated FLIRT signature file, copying it into storage if it isn't already there.

        Args:
            source_path: Path to the generated FLIRT signature file.
            job_id: Optional id of the job that produced this file.

        Returns:
            The absolute path of the file inside storage.
        """
        filename = os.path.basename(source_path)
        stored_path = os.path.join(self.path, filename)

        with self._lock:
            if os.path.abspath(source_path) != os.path.abspath(stored_path):
                shutil.copy2(source_path, stored_path)

            self._index[filename] = {
                "path": stored_path,
                "job_id": job_id,
                "added_at": datetime.now().isoformat(),
            }
            self._save_index()

        self.logger.debug(f"Registered FLIRT signature '{filename}' in server storage")
        return stored_path

    def get_flirt_path(self, filename: str) -> Optional[str]:
        """Return the absolute path to a tracked FLIRT signature, or None if unknown/missing."""
        with self._lock:
            entry = self._index.get(filename)

        if not entry or not os.path.isfile(entry["path"]):
            return None
        return entry["path"]

    def list_files(self) -> List[Dict[str, Any]]:
        """List all tracked FLIRT signatures."""
        with self._lock:
            return [{"filename": filename, **entry} for filename, entry in self._index.items()]
